name: test
on:
  workflow_run:
    workflows: [cicd]
    types:
      - completed
  workflow_dispatch: {}

jobs:

  init:   
    runs-on: ubuntu-latest
    steps:
      - name: print-vars
        run: env
      - name: print-github-context
        run: echo '${{ toJSON(github) }}'
